# Generated by Django 3.2.15 on 2022-10-01 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0025_auto_20221001_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(choices=[('', '予約日'), (datetime.date(2022, 10, 1), datetime.date(2022, 10, 1)), (datetime.date(2022, 10, 2), datetime.date(2022, 10, 2)), (datetime.date(2022, 10, 3), datetime.date(2022, 10, 3)), (datetime.date(2022, 10, 4), datetime.date(2022, 10, 4)), (datetime.date(2022, 10, 5), datetime.date(2022, 10, 5)), (datetime.date(2022, 10, 6), datetime.date(2022, 10, 6)), (datetime.date(2022, 10, 7), datetime.date(2022, 10, 7))], max_length=20, verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_num',
            field=models.IntegerField(choices=[('', '予約人数'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='予約人数'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(choices=[('', '予約時間'), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(21, 0), datetime.time(21, 0))], error_messages={'unique': 'この時間帯はご予約できません。'}, max_length=10, unique=True, verbose_name='予約時間'),
        ),
    ]
